mysite/parts/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	(r'^item_list/','mysite.parts.views.item_list'),
	(r'^contact_list/','mysite.parts.views.contact_list'),
        (r'^user_list/','mysite.parts.views.user_list'),

        (r'^$','mysite.parts.views.index'),
        (r'^items/','mysite.parts.views.items'),
                (r'^onepage/','mysite.parts.views.onepage'),
	(r'^register/','mysite.parts.views.register'),
	(r'^saveuser/','mysite.parts.views.saveuser'),	                       
	(r'^login/','mysite.parts.views.mylogin'),	
	(r'^logout/','mysite.parts.views.mylogout'),
	(r'^afterlogin/','mysite.parts.views.afterlogin'),
	(r'^loginpage/','mysite.parts.views.loginpage'),
         #
    (r'^showcontact/','mysite.parts.views.showcontact'),
	(r'^editcontact/','mysite.parts.views.editcontact'),
	(r'^newcontact/','mysite.parts.views.newcontact'),
	(r'^savecontact/','mysite.parts.views.savecontact'),
	(r'^printcontact/','mysite.parts.views.printcontact'),
	(r'^deletecontact/','mysite.parts.views.deletecontact'),                       
	(r'^finishcontact/','mysite.parts.views.finishcontact'),  

	(r'^server_processing/','mysite.parts.views.server_processing'),
    (r'^ajax/','mysite.parts.views.ajax'),       
    (r'^post/','mysite.parts.views.post'),           
         #
)

mysite/urls.py
from django.conf.urls import patterns, include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from mysite import settings
#from mysite.mygateway import echoGateway
admin.autodiscover()
#myconfig_download_url=r"/photo/"
#download_url="/download/"
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
urlpatterns = patterns('',
    # Example:
    (r'^$', 'mysite.mainview.index'),
    (r'^editor_index$', 'mysite.mainview.editor_index'),
    (r'^custom_editor$', 'mysite.mainview.custom_editor'),
    (r'^data_writer_test.php$', 'mysite.mainview.data_writer_test'),
    (r'^dtable_test.php$', 'mysite.mainview.dtable_test'),
    (r'^searching_test.php$', 'mysite.mainview.searching_test'),
    (r'^sorting_test.php$', 'mysite.mainview.sorting_test'),
    (r'^paging_test.php$', 'mysite.mainview.paging_test'),
    (r'^feeder.php$', 'mysite.mainview.feeder'),
    (r'^receiver.php$', 'mysite.mainview.receiver'),
    (r'^combo_test.php$', 'mysite.mainview.combo_test'),
    (r'^combo_test2.php$', 'mysite.mainview.combo_test2'),
    (r'^combo_test3.php$', 'mysite.mainview.combo_test3'),
    (r'^fetch_brands.php$', 'mysite.mainview.fetch_brands'),
    (r'^fetch_products.php$', 'mysite.mainview.fetch_products'),
	(r'^welcome$', 'mysite.mainview.welcome'),
    (r'^rest/',include('rest.urls')),   
    (r'^parts/',include('mysite.parts.urls')),   
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    #(r'^gateway/', echoGateway),
    (r'^explore/',include('explore.urls')), 
    (r'^accounts/login/$', 'mysite.mainview.loginpage'),
    (r'^login/','mysite.mainview.mylogin'),  
    (r'^logout/','mysite.mainview.mylogout'),
    (r'^afterlogin/','mysite.mainview.afterlogin'),
)
urlpatterns += staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL,view='django.contrib.staticfiles.views.serve')

rest/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
        (r'^$','rest.views.index'),
        (r'^index_2','rest.views.index_2'),
        (r'^application', 'rest.views.application'),
        (r'^item', 'rest.views.item'),
        (r'^contactitem', 'rest.views.contactitem'),
        (r'^contact', 'rest.views.contact'),
        (r'^login', 'rest.views.mylogin'),
        (r'^functions', 'rest.views.functions'),
        (r'^writer', 'rest.views.writer'),
	(r'^app.php_users_view$', 'rest.views.app_users_view'),
	(r'^app.php_users_create$', 'rest.views.app_users_create'),
	(r'^app.php_users_update$', 'rest.views.app_users_update'),
	(r'^app.php_users_destroy$', 'rest.views.app_users_destroy'),  
        (r'^view_item2$', 'rest.views.view_item2'),
        (r'^create_item2$', 'rest.views.create_item2'),
        (r'^update_item2$', 'rest.views.update_item2'),
        (r'^destroy_item2$', 'rest.views.destroy_item2'), 
        (r'^organize$', 'rest.views.organize'), 
        (r'^geticons$', 'rest.views.geticons'), 

)

rest_framework/urls.py
"""
Login and logout views for the browsable API.

Add these to your root URLconf if you're using the browsable API and
your API requires authentication:

    urlpatterns = patterns('',
        ...
        url(r'^auth/', include('rest_framework.urls', namespace='rest_framework'))
    )

The urls must be namespaced as 'rest_framework', and you should make sure
your authentication settings include `SessionAuthentication`.
"""
from __future__ import unicode_literals
from django.conf.urls import patterns, url
from django.contrib.auth import views


template_name = {'template_name': 'rest_framework/login.html'}

urlpatterns = patterns(
    '',
    url(r'^login/$', views.login, template_name, name='login'),
    url(r'^logout/$', views.logout, template_name, name='logout')
)

mysite/parts/models.py
# -*- coding: utf-8 -*-
from django.db import models
import datetime
import logging
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.utils.encoding import python_2_unicode_compatible
class Contact(models.Model):
    #=======销售===========
    yonghu = models.CharField(max_length=30,verbose_name="user")#用户单位
    yiqixinghao=models.CharField(max_length=30,verbose_name="type")#仪器型号
    yiqibh=models.CharField(max_length=30,verbose_name="sn")#仪器编号
    baoxiang =  models.CharField(max_length=30,verbose_name="pack")#包箱
    shenhe =  models.CharField(max_length=30,verbose_name="check")#审核
    yujifahuo_date = models.DateTimeField(verbose_name="send date")#预计发货时间
    hetongbh=models.CharField(max_length=30,verbose_name="contact sn")#合同编号
    def __str__(self):
        return str(self.id)+":"+self.hetongbh
@python_2_unicode_compatible    
class Item(models.Model):
    #ispack=models.BooleanField()
    bh = models.CharField(max_length=30,null=True,blank=True,verbose_name="sn")#库存编号
    name=models.CharField(max_length=30)#备件名称
    name_en=models.CharField(max_length=30,null=True,blank=True)#备件名称
    guige=models.CharField(max_length=30,null=True,blank=True,verbose_name="detail")#规格
    ct=  models.IntegerField(verbose_name="number",default=1)#数量
    danwei =  models.CharField(max_length=30,verbose_name="unit",default="个")#数量单位
    image=models.ImageField(null=True,blank=True,upload_to="item")
    def __str__(self):
        return str(self.id)+":"+self.name+"_"+self.guige+"_"+self.danwei
    class Admin:
        pass
@python_2_unicode_compatible 
class ContactItem(models.Model):
    contact=models.ForeignKey(Contact)#合同
    item=models.ForeignKey(Item)#备件
    ct=  models.IntegerField(verbose_name="number",default=1)#数量
    def __str__(self):
        return self.contact.hetongbh+"_"+self.item.name+"_"+self.item.guige+"_"+str(self.ct)+self.item.danwei
    class Admin:
        pass
class Test2(models.Model):
    ct=  models.IntegerField(verbose_name="number",default=1)#数量
    image=models.ImageField(null=True,upload_to="media")
    def __str__(self):
        return self.contact.hetongbh.encode("utf-8")+"_"+self.item.name.encode("utf-8")+"_"+self.item.guige.encode("utf-8")+"_"+str(self.ct)+self.item.danwei.encode("utf-8")
    class Admin:
        pass
        

mysite/parts/views.py
# Create your views here.
# -*- coding: utf-8 -*-
from mysite.parts.models import *
from django.shortcuts import render_to_response
import time
import os
import logging
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from datetime import datetime
from django.core.exceptions import ObjectDoesNotExist#,DoesNotExist
from django.forms.models  import modelform_factory
import mysite.parts.models
from datetime import datetime
from django.forms import ModelForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.context_processors import csrf
import json as simplejson
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from mysite.parts.serializers import ItemSerializer,ContactSerializer,UserSerializer,ContactItemSerializer
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import generics
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt


@api_view(['GET', 'POST','DELETE'])
def user_list(request, format=None):
    """
    List all users, or create a new user.
    """
    logging.info("-============================")
    logging.info(request.method)
    logging.info(dir(request._request))
    logging.info(request._request)
    if request.method == 'GET':
        ct=User.objects.count()
        serializer = UserSerializer(User.objects.all(), many=True)
        out={"total":ct,"results":serializer.data}
        #logging.info(serializer.data)
        return Response(out)
    elif request.method == 'POST':
        serializer = UserSerializer(data=request.DATA)
        if serializer.is_valid():
            logging.info("save")
            serializer.save()
            serializer.data["clientId"]=request.DATA["id"]
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            logging.info("not save")
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE':
        id1=request.DATA["id"]
        one=User.objects.get(id=int(id1))
        if one!=None:
            logging.info("save")
            one.delete()
            return Response({}, status=status.HTTP_201_CREATED)
        else:
            logging.info("not save")
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
@api_view(['GET', 'POST'])
def item_list(request, format=None):
    """
    List all snippets, or create a new snippet.
    """
    logging.info(dir(request._request))
    logging.info(request._request)
    if request.method == 'GET':
        contact=int(request.GET.get("contact","0"))
        start=int(request.GET.get("start","0"))
        limit=int(request.GET.get("limit","5"))
        ct=ContactItem.objects.filter(contact=contact).count()
        snippets = ContactItem.objects.filter(contact=contact)[start:start+limit]
        serializer = ContactItemSerializer(snippets, many=True)
        out={"total":ct,"results":serializer.data}
        #logging.info(serializer.data)
        return Response(out)
    elif request.method == 'POST':
        serializer = ContactItemSerializer(data=request.DATA)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)            
@api_view(['GET', 'POST'])
def contact_list(request, format=None):
    """
    List all snippets, or create a new snippet.
    """
    logging.info(dir(request._request))
    logging.info(request._request)
    if request.method == 'GET':
        start=int(request.GET.get("start","0"))
        limit=int(request.GET.get("limit","5"))
        ct=Contact.objects.count()
        snippets = Contact.objects.all()[start:start+limit]
        serializer = ContactSerializer(snippets, many=True)
        out={"total":ct,"results":serializer.data}
        #logging.info(serializer.data)
        return Response(out)
    elif request.method == 'POST':
        serializer = ContactSerializer(data=request.DATA)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
def onepage(request):
    logging.info("onepage")
    objects=Contact.objects.all()
    paginator= Paginator(objects, 5)#contact number per page
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        contacts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        contacts = paginator.page(paginator.num_pages)
    r=render_to_response("parts/index.html",{"user":request.user,"contacts":contacts})
    return(r) 
def getCurrentContacts(request):        
    return request.user.contact_set.all()
 
def getCurrentUser(request):
    return request.user
def saveuser(request):
    bh=request.POST["username"]
    password=request.POST["password"]
    try:
        u=User.objects.get(username=bh)
    except ObjectDoesNotExist,e:
        u=User(username=bh)
        u.set_password(password)
        u.save()
        user = authenticate(username=bh, password=password)
        if user is not None:
            login(request, user)
            r=HttpResponseRedirect("/parts/afterlogin")
            return(r)
        else:
            return HttpResponse("login fail")
    else:
        err=bh+" already used by others"
        r=render_to_response("registration/register.html",{"err":err})
    return r
def register(request):
    r=render_to_response("registration/register.html")
    return r

    
def afterlogin(request):
    user=request.user
    dd=Group.objects.get(name="dd")
    if dd in user.groups.all():
        r=HttpResponseRedirect("/parts/")
    else:
        r=HttpResponseRedirect("/parts/")
    return(r)
#@staff_member_required
def loginpage(request):
    c={}
    c.update(csrf(request))
    r=render_to_response("registration/login.html",c)
    return(r)
def mylogin(request):
    username = request.POST['username']
    password = request.POST['password']
    print username,password
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
        r=HttpResponseRedirect("/parts/afterlogin")
        return(r)
        # Redirect to a success page.
    else:
        return HttpResponse("login faile")
        # Return an error message
def mylogout(request):
    logout(request)
    return HttpResponseRedirect("/accounts/login/")
def logout_user(http_request):
    logout(http_request)
 
def login_user(http_request, username, password):
    user = authenticate(username=username, password=password)
    if user is not None:
        login(http_request, user)
        return user
    return None
def items(request):
    logging.info("items")
    objects=Item.objects.all()
    paginator= Paginator(objects, 5)#contact number per page
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        contacts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        contacts = paginator.page(paginator.num_pages)
    r=render_to_response("parts/items.html",{"user":request.user,"contacts":contacts})
    return r
def index(request):
    logging.info("index")
    objects=Contact.objects.order_by('-yujifahuo_date').all()
    logging.info(objects)
    paginator= Paginator(objects, 5)#contact number per page
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        contacts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        contacts = paginator.page(paginator.num_pages)
    r=render_to_response("parts/dd_index.html",{"user":request.user,"contacts":contacts})
##    print dir(r)
    # r.headers["Pragma"]="No-cache"
    # r.headers["Cache-Control"]="no-cache"
    # r.headers["Expires"]="0"
##    print r.headers
    return(r)

def newcontact(request):
    dic = {}
    dic.update(csrf(request))
    dic["new"]="1"
    r=render_to_response("parts/newcontact.html",dic)
    return(r)

def savecontact(request):
    logging.info(request.POST)
    #===============
    new=request.POST["new"]

    yonghu=request.POST["yonghu"]
    yiqixinghao=request.POST["yiqixinghao"]
    yiqibh=request.POST["yiqibh"]
    baoxiang=request.POST["baoxiang"]
    shenhe=request.POST["shenhe"]
    yujifahuo_date=request.POST["yujifahuo_date"]
    hetongbh=request.POST["hetongbh"]

    if new=="1":
        c=Contact(yonghu=yonghu,yiqixinghao=yiqixinghao,yiqibh=yiqibh,baoxiang=baoxiang
        ,shenhe=shenhe,yujifahuo_date=yujifahuo_date,hetongbh=hetongbh
         )
        c.save()
    else:
        contact_id=request.POST["contact_id"]
        c=Contact.objects.get(id=contact_id)
        c.yonghu=yonghu
        c.yiqixinghao=yiqixinghao
        c.yiqibh=yiqibh
        c.baoxiang=baoxiang
        c.shenhe=shenhe
        c.yujifahuo_date=yujifahuo_date
        c.hetongbh=hetongbh
        c.save()

templates/parts/contactsample.html
{% extends "base.html" %}
{% block content %}
<p>contact={{ contact.contactbh }} inclues samples:</p>
<table border="1" cellpadding="2" cellspacing="2"  border="1" >
<tbody>
<td>样品名称</td><td>id</td><td>操作</td><td>数量</td>
{% for c in samples %}
<tr>
<td>{{ c.sample_name }}</td>
<td>{{ c.id }}</td>
<td>
<p>
<a href="/dd/showsampleitems?id={{ c.id }}&contactid={{ contact.id }}">
{% if c.item_set.count %}
show items
{% else %}
add items
{% endif %}
</a>
</p>
<p>
<a href="/dd/editsample?id={{ c.id }}&contactid={{ contact.id }}">editsample</a>
</p>
<p>
<a href="/dd/deletesample?id={{ c.id }}&contactid={{ contact.id }}">deletesample</a>
</p>
</td>
<td>{{ c.item_set.count }}</td>
</tr>
</tbody>
{% endfor %}
</table>
<p><a href="/dd/newsample?contactid={{ contact.id }}">new</a></p>
{% endblock %}

templates/parts/edititem.html
{% extends "base.html" %}
{% block content %}
<form method="post" action="/dd/updateitem/">{% csrf_token %}
<table border="1" cellpadding="2" cellspacing="2" bgcolor="#99ccff" border="1" bordercolor="#993366">
<tr>
<td><label for="id_username">itemname:</label></td>
<td><input type="text" id="samplename" class="vTextField required" name="itemname" size="15" value={{ item.item_name }} maxlength="30" /></td>
</tr>
</table>
<input type="hidden" name="itemid" value="{{ item.id }}" />
<input type="submit" value="save" />
</form>
{% endblock %}

templates/parts/editsample.html
{% extends "base.html" %}
{% block extrahead %}
<!-- calendar -->
<link rel="stylesheet" type="text/css" href="/static/jscalendar-1.0/calendar-win2k-cold-2.css" />
<script type="text/javascript" src="/static/jscalendar-1.0/calendar.js"></script>
<!-- this is translation file - choose your language here -->
<script type="text/javascript" src="/static/jscalendar-1.0/lang/calendar-pl.js"></script>
<script type="text/javascript" src="/static/jscalendar-1.0/calendar-setup.js"></script>
<!-- /calendar -->
{% endblock %}
{% block content %}
<form action="." method="POST">{% csrf_token %}
<table>
{{ form.as_table }}
</table>
<p><input type="submit" value="Submit"></p>
</form>
<!-- div class="form-row" >
  <label for="id_contact_date_date" class="required">Contact date:</label> 
  
<p class="datetime"> 
   Date: <input type="text" id="id_contact_date_date" class="vDateField required" name="contact_date_date" size="10" value="2006-12-10" maxlength="10" /><br />
   Time: <input type="text" id="id_contact_date_time" class="vTimeField required" name="contact_date_time" size="8" value="20:46:33" maxlength="8" />
</p>
</div --!>
{% endblock %}

templates/parts/fz.html
{% extends "base.html" %}
{% block content %}
<p>
user={{ user.username }} inclues contacts:</p>
<table align="center" border="1"  cellpadding="1" cellspacing="2">
  <tbody>
    <tr>
      <td>bh</td>
      <td>id</td>
      <td>date</td>
      <td>action</td>
      <td>sample count</td>
      <td>state</td>
    </tr>
{% for c in contacts %} <tr>
      <td>{{ c.contactbh }}</td>
      <td>{{ c.id }}</td>
      <td>{{ c.contact_date }}</td>
      <td>
		<p><a href="/dd/fzone?id={{ c.id }}">fz</a></p>
		<p><a href="/dd/finishfz?id={{ c.id }}">finishfz</a></p>
      </td>
      <td>{{ c.sample_set.count }}</td>
      <td>{{ c.state }}</td>
    </tr>
{% endfor %}
  </tbody>
</table>
<p>finished:</p>
<table align="center"  border="1"  cellpadding="1" cellspacing="2">
  <tbody>
    <tr>
      <td>bh</td>
      <td>id</td>
      <td>date</td>
      <td>action</td>
      <td>sample count</td>
      <td>state</td>
    </tr>
{% for c in contacts_finish %} <tr>
      <td>{{ c.contactbh }}</td>
      <td>{{ c.id }}</td>
      <td>{{ c.contact_date }}</td>
      <td>
      		<p><a href="/dd/fzone?id={{ c.id }}">fz</a></p>
      </td>
      <td>{{ c.sample_set.count }}</td>
      <td>{{ c.state }}</td>
    </tr>
{% endfor %}
  </tbody>
</table>
{% endblock %}

templates/parts/fzsampleitem.html
{% extends "base.html" %}
{% block content %}
<p>sample={{ sample.sample_name }} inclues items:</p>
<table border=1>
<tr>
<td>item</td><td>id</td><td>fz</td><td>action</td>
</tf>
{% for i in items %}
<tr>
<td>{{ i.item_name }}</td><td>{{ i.id }}</td><td>{{ i.fz }}</td><td><a href="/dd/fzitem?id={{ i.id }}">edit</a></td>
</tr>
{% endfor %}
</table>
{% endblock %}

templates/parts/newcontact.html
{% extends "base.html" %}
{% block extrahead %}
    <style type="text/css" title="currentStyle">
                @import "/static/DataTables-1.9.4/media/css/demo_page.css";
                @import "/static/DataTables-1.9.4/media/css/demo_table.css";
            </style>
    <link rel="stylesheet" href="/static/jquery-ui-1.10.3.custom/css/ui-lightness/jquery-ui-1.10.3.custom.css" />
    <script type="text/javascript" language="javascript" src="/static/DataTables-1.9.4/media/js/jquery.js"></script>
    <script src="/static/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.min.js"></script>
    <script src="/static/jquery-ui-1.10.3.custom/js/jquery-ui-timepicker-addon.js"></script>
    <script src="/static/newcontact.js"></script>
    <script type="text/javascript" language="javascript" src="/static/DataTables-1.9.4/media/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function() {
            $('#table1').dataTable({"bPaginate": false,"bInfo": false,});
        } );
    </script>
{% endblock %}
{% block content %}
<div>内部编号:{{contact.id}}</div>
<form method="post" action="/parts/savecontact/">{% csrf_token %}
<table    cellpadding="0" cellspacing="0" border="0"  id="table0" width="300" >
<tr>
<td><label >用户名称:</label></td>
<td><input type="text"   name="yonghu"  value={{ contact.yonghu}}></input></td>
</tr>
<tr>
<td><label >仪器型号:</label></td>
<td><input type="text"  	  name="yiqixinghao"  value={{ contact.yiqixinghao }}  ></input></td>
</tr>
<tr>
<td><label >仪器编号:</label></td>
<td><input type="text"   name="yiqibh"  value={{ contact.yiqibh }} ></input></td>
</tr>
<tr>
<td><label >包箱:</label></td>
<td><input type="text"   name="baoxiang"  value={{ contact.baoxiang }} ></input></td>
</tr>
<tr>
<td><label >审核:</label></td>
<td><input type="text"   name="shenhe"  value={{ contact.shenhe }} ></input></td>
</tr>
<tr>
<td><label >预计发货时间:</label></td>
<td><input type="text"  class='datepicker'  name="yujifahuo_date"  value={{ contact.yujifahuo_date|date:"Y-m-d" }} ></input></td>
</tr>
<tr>
<td><label >合同编号:</label></td>
<td><input type="text"   name="hetongbh"  value={{ contact.hetongbh }} ></input></td>
</tr>
</table>
<input type="hidden" name="contact_id" value="{{ contact.id }}" />
<input type="hidden" name="user_id" value="{{ user.id }}" />
<input type="hidden" name="new" value="{{ new }}" />
<input type="submit" value="保存" />
</form>
<table    cellpadding="0" cellspacing="0" border="0" class="display" id="table1" width="100%">
    <thead>
       <td>id</td>
      <td>编号</td>
      <td>名称</td>
       <td>数量</td>
      <td>英文名称</td>
      <td>图片</td>
    </thead>
    <tbody>
{% for c in contact.contactitem_set.all %} 
    <tr>
       <td>{{ c.id }}</td>
      <td>{{ c.item.bh }}</td>
       <td>{{ c.item.name }}</td>
      <td>{{ c.ct }}</td>
      <td>{{ c.item.name_en }}</td>
      <td><img src="/media/{{ c.item.image }}" height="100"></td>
      
    </tr>
{% endfor %}
  </tbody>
</table>
{% endblock %}

templates/parts/showcontact.html
{% extends "base.html" %}
{% block extrahead %}
{% endblock %}
{% block content %}
<p></p>
<table    cellpadding="0" cellspacing="0" border="1"  id="table0" width="300" >
<tr>
<td>用户名称:</td>
<td>{{ contact.yonghu}}</td>
</tr>
<tr>
<td><label >仪器型号:</label></td>
<td>{{ contact.yiqixinghao }}</td>
</tr>
<tr>
<td><label >仪器编号:</label></td>
<td>{{ contact.yiqibh }}</td>
</tr>
<tr>
<td><label >包箱:</label></td>
<td>{{ contact.baoxiang }}</td>
</tr>
<tr>
<td><label >审核:</label></td>
<td>{{ contact.shenhe }}</td>
</tr>
<tr>
<td><label >预计发货时间:</label></td>
<td>{{ contact.yujifahuo_date|date:"Y-m-d" }}</td>
</tr>
<tr>
<td><label >合同编号:</label></td>
<td>{{ contact.hetongbh }}</td>
</tr>
</table>
<p></p>
<table    cellpadding="0" cellspacing="0" border="1" class="display" id="table1" width="600">
    <thead>
      <td>库存编号</td>
      <td>配件名称</td>
      <td>规格</td>
      <td>数量</td>
      <td>备货</td>
      <td>备注</td>
    </thead>
    <tbody>
{% for c in contact.contactitem_set.all %} 
    <tr>
      <td>{{ c.item.bh }}</td>
      <td>{{ c.item.name }}</td>
      <td>{{ c.item.guige }}</td>
      <td>{{ c.ct }}{{ c.item.danwei }}</td>
      <td></td>
      <td></td>
    </tr>
{% endfor %}
  </tbody>
</table>
{% endblock %}